apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  influxdb.yaml: |
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      url: http://influxdb-service:8086
      database: metrics_db
      user: admin_user
      password: admin_password
      isDefault: true
      jsonData:
        httpMethod: POST
      secureJsonData:
        password: "${INFLUXDB_ADMIN_PASSWORD}" # в реальной системе нужно более безопасное решение