apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
data:
  admin_user: <base64-encoded-influxdb-admin-username>
  admin_password: <base64-encoded-influxdb-admin-password>
  db_name: <base64-encoded-influxdb-database-name>